version: "3"
services:
  db:
    image: postgres:latest
    container_name: local-postgres-music-catalog
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: lupa123
      POSTGRES_DB: music-catalog

    volumes:
      - ./docker-postgres-data:/var/lib/postgresql/data
